### ISSUE TITLE
Broken link on readme.md

### ISSUE THREAD

**Issue by surak** [deeplearning540/lesson01#1]
readme.md mentions 

`To view the slides, consult [deeplearning540.github.io/lesson00](https://deeplearning540.github.io/lesson00).`

I guess it's lesson01 ?

**Comment by psteinb** [comment]
Thanks, @surak ! I fixed this with https://github.com/deeplearning540/lesson01/commit/b0a4762eb8d922686cf36a01aa6f0ef7e2952bad
